version: "3"
services:
    todo-app:
        container_name: todo-app
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_HOST: db_host
            API_HOST: https://host_ip:8000
        ports:
            - "8000:8000"